# Placeholder
# {DISPLAY_NAME}
# {USERNAME}
# {MESSAGE}

TeamChat:
  pattern: "§7[§bTeam§7]§r {DISPLAY_NAME}: {MESSAGE}"
  toggleEnabledMessage: "Enabled auto chat for TeamChat"
  toggleDisabledMessage: "Disabled auto chat for TeamChat"

LeadChat:
  pattern: "§7[§cLeitung§7]§r {DISPLAY_NAME}: {MESSAGE}"
  toggleEnabledMessage: "Enabled auto chat for LeadChat"
  toggleDisabledMessage: "Disabled auto chat for LeadChat"

