name: TeamChat
main: de.maurice.teamchat.Main
version: 1
api-version: 1.21.3
author: Maurice_009

commands:
  teamchat:
    description: "Write in Teamchat"
    aliases:
      - tc
      - tchat
    permission: "teamchat.chat.team"
    usage: "Usage: /<command> <message>\nUsage: /<command> to toggle chat"
  leadchat:
    description: "Write in Leadchat"
    aliases:
      - lc
      - lchat
    permission: "teamchat.chat.lead"
    usage: "Usage: /<command> <message>\nUsage: /<command> to toggle chat"
  teamchatreload:
    description: "Reloads the config"
    aliases:
      - tcreload
      - tchatreload
    permission: "teamchat.reload"
    usage: "Usage: /<command>"


permissions:
  teamchat.chat.team:
    default: op
  teamchat.chat.lead:
    default: op
  teamchat.receive.team:
    default: op
  teamchat.receive.lead:
    default: op
  teamchat.reload:
    default: op
